### ISSUE TITLE
 Sometimes an exception SessionNotCreatedException occurs

### ISSUE THREAD

**Issue by weixiaokang** [alcounit/selenosis#8]
Thank you for providing such a useful tool so that I can use the browser cluster in K8s. However, I found that the tool sometimes has an exception SessionNotCreatedException. I have no idea about this question. So I came to consult you specially.
For example, if I run 10 browsers concurrently, 1~4 browsers will generate this exception. Sometimes after a period of time is not used, the first run will fail.

Code generates exception information:
```
十二月 16, 2020 8:43:09 下午 org.openqa.selenium.remote.ProtocolHandshake createSession
信息: Detected dialect: W3C
Exception in thread "Thread-7" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities {browserName: chrome, enableVNC: true, version: 87.0}
```

selenosis log:
```
time="2020-12-16T12:43:11Z" level=error msg="session failed: Post \"http://selenoid-vnc-chrome-87-0-28d2e645-1c16-4cec-b32e-71e09d56fd8a.seleniferous:4445/wd/hub/session\": dial tcp: lookup selenoid-vnc-chrome-87-0-28d2e645-1c16-4cec-b32e-71e09d56fd8a.seleniferous on 10.96.0.10:53: no such host" request="POST /wd/hub/session" request_id=39044a18-5a4e-4cb8-bc52-d6fcb9e2dc5c time_elapsed=9.51s
```

**Comment by weixiaokang** [comment]
I think the direct reason is that the Pod was not created successfully. In the case of concurrency related to insufficient resources, I tried to reduce the request cpu to 0.2. Adding a node to k8s can reduce the error probability. But running a single browser still occasionally fails. And I found a temporary solution, catching SessionNotCreatedException and re-applying the browser can solve my problem.
like this:
```
runChrome() {
    try {
        // Request a browser
    } catch(SessionNotCreatedException e) {
        runChrome();
    }
}
```

**Comment by alcounit** [comment]
Hi, thank you for feedback. Could you please update your selenosis deployment manifest with new image **alcounit/selenosis:v0.0.2-develop** and perform redeploy of selenosis deployment.
Looks like it is fixed in https://github.com/alcounit/selenosis/commit/f1a7c7c60c059defd2336d809a19bc3e8534229f#diff-c3e875a7134b2a8273f4d56f0941a4d20431a4c8a0e2bf5c5f651a538490f480

**Comment by alcounit** [comment]
@weixiaokang please let me know if the problem solved

**Comment by alcounit** [comment]
> Hi, thank you for feedback. Could you please update your selenosis deployment manifest with new image **alcounit/selenosis:v0.0.2-develop** and perform redeploy of selenosis deployment.
> Looks like it is fixed in [f1a7c7c#diff-c3e875a7134b2a8273f4d56f0941a4d20431a4c8a0e2bf5c5f651a538490f480](https://github.com/alcounit/selenosis/commit/f1a7c7c60c059defd2336d809a19bc3e8534229f#diff-c3e875a7134b2a8273f4d56f0941a4d20431a4c8a0e2bf5c5f651a538490f480)
I've reworked pod wait logic once again, bcoz looks like the previous solution has significant pressure on k8 API, commit: https://github.com/alcounit/selenosis/commit/698c89fe9215b3f7159bc51c8018686718dc6192#diff-c3e875a7134b2a8273f4d56f0941a4d20431a4c8a0e2bf5c5f651a538490f480

Can you please try with image **alcounit/selenosis:v0.0.3-develop** 
I've tested this image with 10 parallels sessions run on GCP(no limits were added during the test), all browsers started without issues and processed sessions.
GCP cluster config: 3 Nodes | 6 vCPUs | 12.00 GB

**Comment by weixiaokang** [comment]
@alcounit I updated the image to alcounit/selenosis:v0.0.3-develop, but the problem still exists.
The k8s cluster I use is self-built, 3 Nodes | 8 vCPUS | 16GB. I think the machine resources are sufficient, because I applied for moon for a one-month trial, and running 10 browsers concurrently on moon is no problem.
On selenosis, several pods fail to start, and the pod status is Terminating.

On selenosis, when the test task just started, kubectl get pod -n selenosis：
```
selenoid-ui-797c54fbcd-pbf7k                                    2/2     Running             0          5d17h
selenoid-vnc-chrome-87-0-2a5f1b88-e637-44fe-a432-fae61ec92f66   2/2     Running             0          17s
selenoid-vnc-chrome-87-0-3ad8ef54-114e-487f-a267-5c278941528a   2/2     Running             0          18s
selenoid-vnc-chrome-87-0-5dfeb0e4-57f7-4e45-97dd-7fc784f38aa6   2/2     Terminating         0          17s
selenoid-vnc-chrome-87-0-632d63b2-efe1-4b27-a84e-10c251ff2e95   0/2     ContainerCreating   0          7s
selenoid-vnc-chrome-87-0-691aec27-e822-4952-bfd3-e2d1a835617a   2/2     Running             0          16s
selenoid-vnc-chrome-87-0-6a2b5d73-09f5-4653-bc04-f639ab686e71   2/2     Terminating         0          6s
selenoid-vnc-chrome-87-0-752d4d5c-4e96-4062-aa45-2d499126d5bb   2/2     Running             0          17s
selenoid-vnc-chrome-87-0-bfad7c37-fbf5-45f3-99c1-23ffa4afbe5f   2/2     Running             0          17s
selenoid-vnc-chrome-87-0-c3a8fd98-ab20-47d9-b5b7-43f884ab38c9   2/2     Running             0          16s
selenoid-vnc-chrome-87-0-d510fee9-15b0-443b-bbf8-23c876428d5d   0/2     Terminating         0          18s
selenoid-vnc-chrome-87-0-da87bae1-e5e1-43ac-a91a-da5bb5676faa   0/2     Terminating         0          9s
selenoid-vnc-chrome-87-0-e9d9c960-d4e7-4aec-8007-7eed0c5ee607   2/2     Running             0          16s
selenoid-vnc-chrome-87-0-f3b4049a-e2dc-49de-b64e-1cd6cc53dabd   0/2     ContainerCreating   0          3s
selenoid-vnc-chrome-87-0-f99a697e-b76e-4865-98a3-1e437cc31946   2/2     Running             0          17s
selenosis-689dfcff87-5dscc                                      1/1     Running             0          18h
```
On moon，when the test task just started, kubectl get pod -n selenosis：
```
chrome-87-0-1e428a0b-a5f5-418f-add2-ec5e701c70c6   2/2     Running             0          11s
chrome-87-0-36edb327-41e4-4ec2-90ef-d7f8d490db37   0/2     ContainerCreating   0          11s
chrome-87-0-485247e8-04f9-493b-9359-6ddebac79a82   2/2     Running             0          11s
chrome-87-0-7b6e9e19-a5c8-4ca0-82fd-9a20af2b1849   2/2     Running             0          11s
chrome-87-0-c5d8eab4-988e-47ec-a77d-cc24b1759921   2/2     Running             0          11s
chrome-87-0-cac85064-84ac-4eb1-81b6-9008e21fd15a   2/2     Running             0          11s
chrome-87-0-e0a6d281-936f-4252-8efa-22e3c800c5b7   2/2     Running             0          11s
chrome-87-0-e7974810-e019-42fe-b09a-75d73fcf95b4   2/2     Running             0          11s
chrome-87-0-edcd2545-b003-4d41-98b1-c63a1eb6a89d   2/2     Running             0          11s
chrome-87-0-ee339d8b-ca3c-4a44-94a9-6b08207d2ecf   2/2     Running             0          11s
moon-584f74cc4c-pvmz4                              3/3     Running             0          45m
moon-584f74cc4c-vrr65                              3/3     Running             0          45m

```

**Comment by weixiaokang** [comment]
My k8s version：
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:40:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by alcounit** [comment]
@weixiaokang is your last run was with applied limits?
Anyway, can you please share selenosis log, browsers config, and logs from browsers you can do it by running **[stern](https://github.com/wercker/stern)**
stern --selector type=browser  --namespace selenosis -c seleniferous

**Comment by weixiaokang** [comment]
@alcounit 
My test code just like this:
```
for (int i = 0; i < 10; i++) {
      runChrome();
}
```
```
public void runChrome() {
    new Thread(() -> {
          // open website
         Thread.sleep(30000);
         driver.quit();
    }).start();
}
```
selenosis log:
```
time="2020-12-21T10:28:14Z" level=info msg=session request="POST /wd/hub/session" request_id=5c5d9a99-13b0-43b1-8616-0530efc253ed time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg="starting browser from image: selenoid/vnc:chrome_87.0" request="POST /wd/hub/session" request_id=5c5d9a99-13b0-43b1-8616-0530efc253ed time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg=session request="POST /wd/hub/session" request_id=985f459d-7271-4946-ba82-76af0c227cca time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg="starting browser from image: selenoid/vnc:chrome_87.0" request="POST /wd/hub/session" request_id=985f459d-7271-4946-ba82-76af0c227cca time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg=session request="POST /wd/hub/session" request_id=01c32411-8642-414d-94a8-c8f330180abe time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg="starting browser from image: selenoid/vnc:chrome_87.0" request="POST /wd/hub/session" request_id=01c32411-8642-414d-94a8-c8f330180abe time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg=session request="POST /wd/hub/session" request_id=1c24677a-74df-468c-bb78-736242372b12 time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg="starting browser from image: selenoid/vnc:chrome_87.0" request="POST /wd/hub/session" request_id=1c24677a-74df-468c-bb78-736242372b12 time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg=session request="POST /wd/hub/session" request_id=7dca9140-db15-49d0-a091-7ab3d2edb57f time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg="starting browser from image: selenoid/vnc:chrome_87.0" request="POST /wd/hub/session" request_id=7dca9140-db15-49d0-a091-7ab3d2edb57f time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg=session request="POST /wd/hub/session" request_id=0f8c6cac-0dfe-403b-a5d2-e2faebf5404e time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg="starting browser from image: selenoid/vnc:chrome_87.0" request="POST /wd/hub/session" request_id=0f8c6cac-0dfe-403b-a5d2-e2faebf5404e time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg=session request="POST /wd/hub/session" request_id=06dc2bf3-dfcf-4401-83a4-8020a354999d time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg="starting browser from image: selenoid/vnc:chrome_87.0" request="POST /wd/hub/session" request_id=06dc2bf3-dfcf-4401-83a4-8020a354999d time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg=session request="POST /wd/hub/session" request_id=fa150040-86c1-4224-9e5c-21416b1d9f5c time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg="starting browser from image: selenoid/vnc:chrome_87.0" request="POST /wd/hub/session" request_id=fa150040-86c1-4224-9e5c-21416b1d9f5c time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg=session request="POST /wd/hub/session" request_id=ac07bdbe-d0dd-4399-a9e5-6f9a428113d5 time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg="starting browser from image: selenoid/vnc:chrome_87.0" request="POST /wd/hub/session" request_id=ac07bdbe-d0dd-4399-a9e5-6f9a428113d5 time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg=session request="POST /wd/hub/session" request_id=260bbd18-a1ee-462e-b207-ad219b49d702 time_elapsed=0.00s
time="2020-12-21T10:28:14Z" level=info msg="starting browser from image: selenoid/vnc:chrome_87.0" request="POST /wd/hub/session" request_id=260bbd18-a1ee-462e-b207-ad219b49d702 time_elapsed=0.00s
I1221 10:28:15.531550       1 request.go:645] Throttling request took 1.192647775s, request: POST:https://10.96.0.1:443/api/v1/namespaces/selenosis/pods
time="2020-12-21T10:28:18Z" level=error msg="session failed: Post \"http://selenoid-vnc-chrome-87-0-861fe5c8-402e-447c-9e36-a673286cc94c.seleniferous:4445/wd/hub/session\": dial tcp: lookup selenoid-vnc-chrome-87-0-861fe5c8-402e-447c-9e36-a673286cc94c.seleniferous on 10.96.0.10:53: no such host" request="POST /wd/hub/session" request_id=985f459d-7271-4946-ba82-76af0c227cca time_elapsed=4.41s
time="2020-12-21T10:28:19Z" level=info msg="browser sessionId: selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc" request="POST /wd/hub/session" request_id=0f8c6cac-0dfe-403b-a5d2-e2faebf5404e time_elapsed=4.81s
time="2020-12-21T10:28:19Z" level=info msg="proxying session" request="POST /wd/hub/session/selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc/window/maximize" request_id=4f5fbbb6-6d6e-4a69-a550-984085b81812 session_id=selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc
time="2020-12-21T10:28:19Z" level=info msg="proxying session" request="POST /wd/hub/session/selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc/url" request_id=572bdc31-4ba5-43a9-a731-3d294ddb07fe session_id=selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc
time="2020-12-21T10:28:19Z" level=info msg="browser sessionId: selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934" request="POST /wd/hub/session" request_id=01c32411-8642-414d-94a8-c8f330180abe time_elapsed=5.30s
time="2020-12-21T10:28:19Z" level=info msg="proxying session" request="POST /wd/hub/session/selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934/window/maximize" request_id=f2bec5ee-61e5-400c-b708-6f83ebb5f630 session_id=selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934
time="2020-12-21T10:28:19Z" level=info msg="proxying session" request="POST /wd/hub/session/selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934/url" request_id=ce733871-989f-4939-b968-a338b204e2c9 session_id=selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934
time="2020-12-21T10:28:20Z" level=error msg="session failed: Post \"http://selenoid-vnc-chrome-87-0-af3177a0-5052-45be-b4e4-9462146e4633.seleniferous:4445/wd/hub/session\": dial tcp: lookup selenoid-vnc-chrome-87-0-af3177a0-5052-45be-b4e4-9462146e4633.seleniferous on 10.96.0.10:53: no such host" request="POST /wd/hub/session" request_id=fa150040-86c1-4224-9e5c-21416b1d9f5c time_elapsed=5.73s
time="2020-12-21T10:28:20Z" level=error msg="session failed: Post \"http://selenoid-vnc-chrome-87-0-989bf1cb-fa34-4dfe-9b8e-6a7b09c7364d.seleniferous:4445/wd/hub/session\": dial tcp: lookup selenoid-vnc-chrome-87-0-989bf1cb-fa34-4dfe-9b8e-6a7b09c7364d.seleniferous on 10.96.0.10:53: no such host" request="POST /wd/hub/session" request_id=260bbd18-a1ee-462e-b207-ad219b49d702 time_elapsed=5.98s
time="2020-12-21T10:28:22Z" level=error msg="session failed: Post \"http://selenoid-vnc-chrome-87-0-2c76bf8a-efdb-4ad4-b1d4-320eb2fefa46.seleniferous:4445/wd/hub/session\": dial tcp: lookup selenoid-vnc-chrome-87-0-2c76bf8a-efdb-4ad4-b1d4-320eb2fefa46.seleniferous on 10.96.0.10:53: no such host" request="POST /wd/hub/session" request_id=5c5d9a99-13b0-43b1-8616-0530efc253ed time_elapsed=7.91s
time="2020-12-21T10:28:22Z" level=info msg="proxying session" request="GET /wd/hub/session/selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc/title" request_id=3de0702a-d5c7-44c5-9ada-88c101071686 session_id=selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc
time="2020-12-21T10:28:24Z" level=error msg="session failed: Post \"http://selenoid-vnc-chrome-87-0-2b120781-00ab-407e-98f7-94c22ad2da47.seleniferous:4445/wd/hub/session\": dial tcp: lookup selenoid-vnc-chrome-87-0-2b120781-00ab-407e-98f7-94c22ad2da47.seleniferous on 10.96.0.10:53: no such host" request="POST /wd/hub/session" request_id=7dca9140-db15-49d0-a091-7ab3d2edb57f time_elapsed=9.79s
time="2020-12-21T10:28:24Z" level=info msg="browser sessionId: selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a" request="POST /wd/hub/session" request_id=1c24677a-74df-468c-bb78-736242372b12 time_elapsed=10.40s
time="2020-12-21T10:28:24Z" level=info msg="proxying session" request="POST /wd/hub/session/selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a/window/maximize" request_id=36d849c8-c1b9-4745-a1b0-a12c56e95d48 session_id=selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a
time="2020-12-21T10:28:24Z" level=info msg="proxying session" request="GET /wd/hub/session/selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934/title" request_id=7fff52fc-2104-4cc2-9e10-eab7c4611d47 session_id=selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934
time="2020-12-21T10:28:24Z" level=info msg="proxying session" request="POST /wd/hub/session/selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a/url" request_id=e9d47021-702c-4e5f-b163-86311c67500d session_id=selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a
time="2020-12-21T10:28:27Z" level=info msg="proxying session" request="GET /wd/hub/session/selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a/title" request_id=90405f36-8120-4ca3-9281-457c4352e1ac session_id=selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a
time="2020-12-21T10:28:27Z" level=info msg="browser sessionId: selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471" request="POST /wd/hub/session" request_id=06dc2bf3-dfcf-4401-83a4-8020a354999d time_elapsed=13.34s
time="2020-12-21T10:28:27Z" level=info msg="browser sessionId: selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab" request="POST /wd/hub/session" request_id=ac07bdbe-d0dd-4399-a9e5-6f9a428113d5 time_elapsed=13.36s
time="2020-12-21T10:28:27Z" level=info msg="proxying session" request="POST /wd/hub/session/selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471/window/maximize" request_id=8ce1afa9-b7bf-446d-ac64-2a6b57ee6819 session_id=selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471
time="2020-12-21T10:28:27Z" level=info msg="proxying session" request="POST /wd/hub/session/selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab/window/maximize" request_id=d48cb930-0993-45bd-abd2-0091ebdc4e6a session_id=selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab
time="2020-12-21T10:28:27Z" level=info msg="proxying session" request="POST /wd/hub/session/selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471/url" request_id=3300994a-599f-45b5-9572-f5c153299bbe session_id=selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471
time="2020-12-21T10:28:27Z" level=info msg="proxying session" request="POST /wd/hub/session/selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab/url" request_id=908f2e3f-d96f-4a47-ab30-b7831944bfb3 session_id=selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab
time="2020-12-21T10:28:29Z" level=info msg="proxying session" request="GET /wd/hub/session/selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471/title" request_id=a4fc4020-63eb-4c8c-9637-9ce25bac0313 session_id=selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471
time="2020-12-21T10:28:29Z" level=info msg="proxying session" request="GET /wd/hub/session/selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab/title" request_id=6bd218ac-655c-40a1-91c2-6c0c9081e339 session_id=selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab
time="2020-12-21T10:28:52Z" level=info msg="proxying session" request="DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc" request_id=8ef0c4cb-fd3b-4931-9be7-49788fc9ad10 session_id=selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc
time="2020-12-21T10:28:54Z" level=info msg="proxying session" request="DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934" request_id=2d95e436-575c-4b61-b505-dfb5f677345e session_id=selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934
time="2020-12-21T10:28:57Z" level=info msg="proxying session" request="DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a" request_id=76564056-26ab-46af-a56b-5ff5d14ab84c session_id=selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a
time="2020-12-21T10:28:59Z" level=info msg="proxying session" request="DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471" request_id=90dc085c-81ba-4924-8093-839b746a6231 session_id=selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471
time="2020-12-21T10:28:59Z" level=info msg="proxying session" request="DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab" request_id=159a696f-fc27-4e9a-9ff1-912d33a82686 session_id=selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab
```
logs from browsers:
```
+ selenoid-vnc-chrome-87-0-861fe5c8-402e-447c-9e36-a673286cc94c › seleniferous
selenoid-vnc-chrome-87-0-861fe5c8-402e-447c-9e36-a673286cc94c seleniferous {"level":"info","msg":"starting seleniferous v0.0.1-develop","time":"2020-12-21T10:28:16Z"}
selenoid-vnc-chrome-87-0-861fe5c8-402e-447c-9e36-a673286cc94c seleniferous {"level":"info","msg":"kubernetes client created","time":"2020-12-21T10:28:16Z"}
+ selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 › seleniferous
+ selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc › seleniferous
selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 seleniferous {"level":"info","msg":"starting seleniferous v0.0.1-develop","time":"2020-12-21T10:28:16Z"}
selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 seleniferous {"level":"info","msg":"kubernetes client created","time":"2020-12-21T10:28:16Z"}
selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc seleniferous {"level":"info","msg":"starting seleniferous v0.0.1-develop","time":"2020-12-21T10:28:17Z"}
selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc seleniferous {"level":"info","msg":"kubernetes client created","time":"2020-12-21T10:28:17Z"}
selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 seleniferous {"level":"info","msg":"new session request","request":"POST /wd/hub/session","request_by":"selenosis-689dfcff87-vjv4z","request_id":"45f06856-3cf1-47fd-959b-cb04fdfde352","time":"2020-12-21T10:28:18Z"}
+ selenoid-vnc-chrome-87-0-af3177a0-5052-45be-b4e4-9462146e4633 › seleniferous
+ selenoid-vnc-chrome-87-0-989bf1cb-fa34-4dfe-9b8e-6a7b09c7364d › seleniferous
selenoid-vnc-chrome-87-0-af3177a0-5052-45be-b4e4-9462146e4633 seleniferous {"level":"info","msg":"starting seleniferous v0.0.1-develop","time":"2020-12-21T10:28:17Z"}
selenoid-vnc-chrome-87-0-af3177a0-5052-45be-b4e4-9462146e4633 seleniferous {"level":"info","msg":"kubernetes client created","time":"2020-12-21T10:28:17Z"}
selenoid-vnc-chrome-87-0-989bf1cb-fa34-4dfe-9b8e-6a7b09c7364d seleniferous {"level":"info","msg":"starting seleniferous v0.0.1-develop","time":"2020-12-21T10:28:18Z"}
selenoid-vnc-chrome-87-0-989bf1cb-fa34-4dfe-9b8e-6a7b09c7364d seleniferous {"level":"info","msg":"kubernetes client created","time":"2020-12-21T10:28:18Z"}
selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc seleniferous {"level":"info","msg":"new session request","request":"POST /wd/hub/session","request_by":"selenosis-689dfcff87-vjv4z","request_id":"c44c57c0-3b4a-48fd-b496-63191b952928","time":"2020-12-21T10:28:18Z"}
selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc seleniferous {"level":"info","msg":"new session request completed: 000b92b47fa34cc58587715450c1d183","request":"POST /wd/hub/session","request_by":"selenosis-689dfcff87-vjv4z","request_id":"c44c57c0-3b4a-48fd-b496-63191b952928","time":"2020-12-21T10:28:19Z"}
selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc seleniferous {"level":"info","msg":"proxy session","request":"POST /wd/hub/session/selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc/window/maximize","request_by":"selenosis-689dfcff87-vjv4z","request_id":"546a7c34-4ab6-43ec-b3fa-ae6c20faaa0d","time":"2020-12-21T10:28:19Z"}
selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc seleniferous {"level":"info","msg":"proxy session","request":"POST /wd/hub/session/selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc/url","request_by":"selenosis-689dfcff87-vjv4z","request_id":"3fbe8667-03c5-48c8-b852-f601fb9cd5b4","time":"2020-12-21T10:28:19Z"}
selenoid-vnc-chrome-87-0-861fe5c8-402e-447c-9e36-a673286cc94c seleniferous {"level":"warning","msg":"stopping seleniferous","time":"2020-12-21T10:28:19Z"}
selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 seleniferous {"level":"info","msg":"new session request completed: cf9214884a4dff52a40309115dd0a2d5","request":"POST /wd/hub/session","request_by":"selenosis-689dfcff87-vjv4z","request_id":"45f06856-3cf1-47fd-959b-cb04fdfde352","time":"2020-12-21T10:28:19Z"}
selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 seleniferous {"level":"info","msg":"proxy session","request":"POST /wd/hub/session/selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934/window/maximize","request_by":"selenosis-689dfcff87-vjv4z","request_id":"b3419864-1570-4a5a-9661-258a366a674d","time":"2020-12-21T10:28:19Z"}
selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 seleniferous {"level":"info","msg":"proxy session","request":"POST /wd/hub/session/selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934/url","request_by":"selenosis-689dfcff87-vjv4z","request_id":"b7370531-dcbf-4805-b03b-0bfb870ca0b6","time":"2020-12-21T10:28:19Z"}
selenoid-vnc-chrome-87-0-af3177a0-5052-45be-b4e4-9462146e4633 seleniferous {"level":"warning","msg":"stopping seleniferous","time":"2020-12-21T10:28:20Z"}
+ selenoid-vnc-chrome-87-0-2c76bf8a-efdb-4ad4-b1d4-320eb2fefa46 › seleniferous
selenoid-vnc-chrome-87-0-989bf1cb-fa34-4dfe-9b8e-6a7b09c7364d seleniferous {"level":"warning","msg":"stopping seleniferous","time":"2020-12-21T10:28:21Z"}
selenoid-vnc-chrome-87-0-2c76bf8a-efdb-4ad4-b1d4-320eb2fefa46 seleniferous {"level":"info","msg":"starting seleniferous v0.0.1-develop","time":"2020-12-21T10:28:19Z"}
selenoid-vnc-chrome-87-0-2c76bf8a-efdb-4ad4-b1d4-320eb2fefa46 seleniferous {"level":"info","msg":"kubernetes client created","time":"2020-12-21T10:28:19Z"}
selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc seleniferous {"level":"info","msg":"proxy session","request":"GET /wd/hub/session/selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc/title","request_by":"selenosis-689dfcff87-vjv4z","request_id":"f7c34862-fa0c-44c5-b1a3-e323e604a46b","time":"2020-12-21T10:28:22Z"}
+ selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a › seleniferous
selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a seleniferous {"level":"info","msg":"starting seleniferous v0.0.1-develop","time":"2020-12-21T10:28:21Z"}
selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a seleniferous {"level":"info","msg":"kubernetes client created","time":"2020-12-21T10:28:21Z"}
selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a seleniferous {"level":"info","msg":"new session request","request":"POST /wd/hub/session","request_by":"selenosis-689dfcff87-vjv4z","request_id":"66b2fa19-fbcc-432d-9caf-73113c378f47","time":"2020-12-21T10:28:23Z"}
+ selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab › seleniferous
selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab seleniferous {"level":"info","msg":"starting seleniferous v0.0.1-develop","time":"2020-12-21T10:28:22Z"}
selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab seleniferous {"level":"info","msg":"kubernetes client created","time":"2020-12-21T10:28:22Z"}
+ selenoid-vnc-chrome-87-0-2b120781-00ab-407e-98f7-94c22ad2da47 › seleniferous
+ selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 › seleniferous
selenoid-vnc-chrome-87-0-2b120781-00ab-407e-98f7-94c22ad2da47 seleniferous {"level":"info","msg":"starting seleniferous v0.0.1-develop","time":"2020-12-21T10:28:21Z"}
selenoid-vnc-chrome-87-0-2b120781-00ab-407e-98f7-94c22ad2da47 seleniferous {"level":"info","msg":"kubernetes client created","time":"2020-12-21T10:28:21Z"}
selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 seleniferous {"level":"info","msg":"starting seleniferous v0.0.1-develop","time":"2020-12-21T10:28:22Z"}
selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 seleniferous {"level":"info","msg":"kubernetes client created","time":"2020-12-21T10:28:22Z"}
selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab seleniferous {"level":"info","msg":"new session request","request":"POST /wd/hub/session","request_by":"selenosis-689dfcff87-vjv4z","request_id":"0d8ad6a0-472b-492b-ae8d-252c5eba0e47","time":"2020-12-21T10:28:23Z"}
selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 seleniferous {"level":"info","msg":"new session request","request":"POST /wd/hub/session","request_by":"selenosis-689dfcff87-vjv4z","request_id":"4123d2cc-99e6-4fd7-81a0-ac473febede0","time":"2020-12-21T10:28:23Z"}
selenoid-vnc-chrome-87-0-2c76bf8a-efdb-4ad4-b1d4-320eb2fefa46 seleniferous {"level":"warning","msg":"stopping seleniferous","time":"2020-12-21T10:28:24Z"}
selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a seleniferous {"level":"info","msg":"new session request completed: 799ad79c017caecaec793d78d7144bd3","request":"POST /wd/hub/session","request_by":"selenosis-689dfcff87-vjv4z","request_id":"66b2fa19-fbcc-432d-9caf-73113c378f47","time":"2020-12-21T10:28:24Z"}
selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a seleniferous {"level":"info","msg":"proxy session","request":"POST /wd/hub/session/selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a/window/maximize","request_by":"selenosis-689dfcff87-vjv4z","request_id":"91712acf-75ae-4130-898e-62a517661b27","time":"2020-12-21T10:28:24Z"}
selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 seleniferous {"level":"info","msg":"proxy session","request":"GET /wd/hub/session/selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934/title","request_by":"selenosis-689dfcff87-vjv4z","request_id":"5f5e67fa-3477-4fb3-874a-171ea10589fe","time":"2020-12-21T10:28:24Z"}
selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a seleniferous {"level":"info","msg":"proxy session","request":"POST /wd/hub/session/selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a/url","request_by":"selenosis-689dfcff87-vjv4z","request_id":"ddec18ac-d307-4bd4-a9eb-c7f5bab734a5","time":"2020-12-21T10:28:24Z"}
selenoid-vnc-chrome-87-0-2b120781-00ab-407e-98f7-94c22ad2da47 seleniferous {"level":"warning","msg":"stopping seleniferous","time":"2020-12-21T10:28:25Z"}
selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a seleniferous {"level":"info","msg":"proxy session","request":"GET /wd/hub/session/selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a/title","request_by":"selenosis-689dfcff87-vjv4z","request_id":"188d788a-0ae5-4cb0-b0ca-65b1a44aead3","time":"2020-12-21T10:28:27Z"}
selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 seleniferous {"level":"info","msg":"new session request completed: b79ec75b462721231c8f828767435cef","request":"POST /wd/hub/session","request_by":"selenosis-689dfcff87-vjv4z","request_id":"4123d2cc-99e6-4fd7-81a0-ac473febede0","time":"2020-12-21T10:28:27Z"}
selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 seleniferous {"level":"info","msg":"proxy session","request":"POST /wd/hub/session/selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471/window/maximize","request_by":"selenosis-689dfcff87-vjv4z","request_id":"34db5810-2b3e-4f1c-9242-617baa558b8b","time":"2020-12-21T10:28:27Z"}
selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 seleniferous {"level":"info","msg":"proxy session","request":"POST /wd/hub/session/selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471/url","request_by":"selenosis-689dfcff87-vjv4z","request_id":"7ae3e8aa-1507-47dc-a849-ff035f8db364","time":"2020-12-21T10:28:27Z"}
selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab seleniferous {"level":"info","msg":"new session request completed: ba6f59d9d1bab9766d780c3ba9c599a4","request":"POST /wd/hub/session","request_by":"selenosis-689dfcff87-vjv4z","request_id":"0d8ad6a0-472b-492b-ae8d-252c5eba0e47","time":"2020-12-21T10:28:27Z"}
selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab seleniferous {"level":"info","msg":"proxy session","request":"POST /wd/hub/session/selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab/window/maximize","request_by":"selenosis-689dfcff87-vjv4z","request_id":"790b883e-91a0-49cd-b1e1-a26f2211c8c0","time":"2020-12-21T10:28:27Z"}
selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab seleniferous {"level":"info","msg":"proxy session","request":"POST /wd/hub/session/selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab/url","request_by":"selenosis-689dfcff87-vjv4z","request_id":"0ea8a401-02a2-487b-a61b-94da988686f2","time":"2020-12-21T10:28:27Z"}
- selenoid-vnc-chrome-87-0-861fe5c8-402e-447c-9e36-a673286cc94c
- selenoid-vnc-chrome-87-0-989bf1cb-fa34-4dfe-9b8e-6a7b09c7364d
- selenoid-vnc-chrome-87-0-af3177a0-5052-45be-b4e4-9462146e4633
selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 seleniferous {"level":"info","msg":"proxy session","request":"GET /wd/hub/session/selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471/title","request_by":"selenosis-689dfcff87-vjv4z","request_id":"91ac3db4-a6e9-4e72-a8e2-9874e55160c4","time":"2020-12-21T10:28:29Z"}
selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab seleniferous {"level":"info","msg":"proxy session","request":"GET /wd/hub/session/selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab/title","request_by":"selenosis-689dfcff87-vjv4z","request_id":"d4199e0c-98d4-492d-9a85-df8987ff6d0b","time":"2020-12-21T10:28:29Z"}
- selenoid-vnc-chrome-87-0-2c76bf8a-efdb-4ad4-b1d4-320eb2fefa46
- selenoid-vnc-chrome-87-0-2b120781-00ab-407e-98f7-94c22ad2da47
selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc seleniferous {"level":"warning","msg":"session selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc delete request","request":"DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc","request_by":"selenosis-689dfcff87-vjv4z","request_id":"fe0de190-ef65-41d4-91ab-7e0c7176c18c","time":"2020-12-21T10:28:52Z"}
selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc seleniferous {"level":"info","msg":"proxy session","request":"DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc","request_by":"selenosis-689dfcff87-vjv4z","request_id":"fe0de190-ef65-41d4-91ab-7e0c7176c18c","time":"2020-12-21T10:28:52Z"}
selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc seleniferous {"level":"warning","msg":"stopping seleniferous","time":"2020-12-21T10:28:52Z"}
selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 seleniferous {"level":"warning","msg":"session selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 delete request","request":"DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934","request_by":"selenosis-689dfcff87-vjv4z","request_id":"bd75aa4d-bd9b-4908-88fe-d202bada03b8","time":"2020-12-21T10:28:54Z"}
selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 seleniferous {"level":"info","msg":"proxy session","request":"DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934","request_by":"selenosis-689dfcff87-vjv4z","request_id":"bd75aa4d-bd9b-4908-88fe-d202bada03b8","time":"2020-12-21T10:28:54Z"}
selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934 seleniferous {"level":"warning","msg":"stopping seleniferous","time":"2020-12-21T10:28:55Z"}
- selenoid-vnc-chrome-87-0-27aabe57-d87b-46b9-ae1d-d1806ca842cc
- selenoid-vnc-chrome-87-0-368d97dd-ca85-4823-91f8-bea248967934
selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a seleniferous {"level":"warning","msg":"session selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a delete request","request":"DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a","request_by":"selenosis-689dfcff87-vjv4z","request_id":"b29685ad-d01d-447a-a1db-a08592569436","time":"2020-12-21T10:28:57Z"}
selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a seleniferous {"level":"info","msg":"proxy session","request":"DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a","request_by":"selenosis-689dfcff87-vjv4z","request_id":"b29685ad-d01d-447a-a1db-a08592569436","time":"2020-12-21T10:28:57Z"}
selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a seleniferous {"level":"warning","msg":"stopping seleniferous","time":"2020-12-21T10:28:57Z"}
selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 seleniferous {"level":"warning","msg":"session selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 delete request","request":"DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471","request_by":"selenosis-689dfcff87-vjv4z","request_id":"92c2fba9-3146-4cca-85fe-68c1ecf43a8f","time":"2020-12-21T10:28:59Z"}
selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 seleniferous {"level":"info","msg":"proxy session","request":"DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471","request_by":"selenosis-689dfcff87-vjv4z","request_id":"92c2fba9-3146-4cca-85fe-68c1ecf43a8f","time":"2020-12-21T10:28:59Z"}
selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab seleniferous {"level":"warning","msg":"session selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab delete request","request":"DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab","request_by":"selenosis-689dfcff87-vjv4z","request_id":"b3d90d31-7cd0-47cf-892e-8e4e89f87758","time":"2020-12-21T10:28:59Z"}
selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab seleniferous {"level":"info","msg":"proxy session","request":"DELETE /wd/hub/session/selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab","request_by":"selenosis-689dfcff87-vjv4z","request_id":"b3d90d31-7cd0-47cf-892e-8e4e89f87758","time":"2020-12-21T10:28:59Z"}
selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471 seleniferous {"level":"warning","msg":"stopping seleniferous","time":"2020-12-21T10:28:59Z"}
selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab seleniferous {"level":"warning","msg":"stopping seleniferous","time":"2020-12-21T10:28:59Z"}
- selenoid-vnc-chrome-87-0-dff582ec-4f59-4abc-bbe8-307985c7715a
- selenoid-vnc-chrome-87-0-a30c8aec-b4c2-497e-9957-c6d18d0e93ab
- selenoid-vnc-chrome-87-0-345b9352-3653-4423-83a5-e7d6a3f58471
```
browsers config:
```
- apiVersion: v1
  data:
    browsers.yaml: |
      chrome:
        defaultVersion: "87.0"
        path: "/"
        versions:
          '85.0':
            image: selenoid/vnc:chrome_85.0
          '86.0':
            image: selenoid/vnc:chrome_86.0
          '87.0':
            image: selenoid/vnc:chrome_87.0
      firefox:
        defaultVersion: "83.0"
        path: "/wd/hub"
        versions:
          '81.0':
            image: selenoid/vnc:firefox_81.0
          '82.0':
            image: selenoid/vnc:firefox_82.0
          '83.0':
            image: selenoid/vnc:firefox_83.0
      opera:
        defaultVersion: "72.0"
        path: "/"
        versions:
          '70.0':
            image: selenoid/vnc:opera_70.0
          '71.0':
            image: selenoid/vnc:opera_71.0
          '72.0':
            image: selenoid/vnc:opera_72.0
  kind: ConfigMap
  metadata:
    creationTimestamp: "2020-12-21T09:29:07Z"
    name: selenosis-config
    namespace: selenosis
    resourceVersion: "188386703"
    selfLink: /api/v1/namespaces/selenosis/configmaps/selenosis-config
    uid: 0ccba6b5-291e-45ca-8a44-58f4a323fe04
```

**Comment by alcounit** [comment]
@weixiaokang looks like this issue reproduced only on k8 cluster with coredns. GKE has kube-dns installed, my local cluster also uses kube-dns and I have no troubles, so I used cluster with coredns and I was able to reproduce the issue.
Can you please update your coredns config map with following

```json
    selenosis.svc.cluster.local:53 {
        errors
        kubernetes cluster.local {
          namespaces selenosis
        }
    }
```
The config should be like this:
```yaml
apiVersion: v1
data:
  Corefile: |
    selenosis.svc.cluster.local:53 {
        errors
        kubernetes cluster.local {
          namespaces selenosis
        }
    }
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
        import custom/*.override
    }
    import custom/*.server
kind: ConfigMap
...
```
To do please use:
```bash
kubectl edit cm coredns -n kube-system
```

selenosis deployment should be restarted after coredns cm update

**Comment by weixiaokang** [comment]
@alcounit Great! This problem is solved, the browser pod is launched very quickly.
What is the difference between coredns and kube-dns which caused this problem?

**Comment by alcounit** [comment]
@weixiaokang great, will update README with instructions.
I really don't know why we have an issue like this when the cluster runs with coredns by default. Good, that it can be resolved easily.
